feat: add paginated credentials, delete credential endpoinst, PATCH method to CORS
0xPolygonID/issuer-node pull request #708
Opened 2024-08-02 14:59 UTC by volodymyr-basiuk

2024-08-02 15:11 UTC, martinsaporiti commented on api/api.yaml
> +              * `all` - All Schemas. (default value)
this should be credentials?

2024-08-02 15:12 UTC, martinsaporiti requested changes
Could you add some tests?

2024-08-04 17:38 UTC, volodymyr-basiuk commented
> Could you add some tests?

added

2024-08-05 09:18 UTC, martinsaporiti approved these changes
LGTM

2024-08-06 09:09 UTC, martinsaporiti approved these changes
LGMT
good work

2024-08-06 09:10 UTC, merged