Pid 2645 implement aws secret storage provider
0xPolygonID/issuer-node pull request #848
Opened 2024-11-19 13:04 UTC by martinsaporiti

2024-11-21 01:29 UTC, OBrezhniev requested changes

2024-11-21 01:29 UTC, OBrezhniev commented on internal/kms/utils_test.go
> +	identity, err := w3c.ParseDID("did:polygonid:polygon:amoy:2qQ68JkRcf3ySMcjPtGKJhGgu7jh4zzhrz6UxpXwPw")
Please use did:iden3

2024-11-21 10:13 UTC, martinsaporiti commented on internal/kms/aws_secret_storage_provider.go
> +	localstackSecretManagerEndpoint = "http://localhost:4566"
1. ok
2. ok
3. I prefer `URL` for the name of the variable. So AWS config will be:
```
ISSUER_KMS_AWS_ACCESS_KEY=<aws_access_key>
ISSUER_KMS_AWS_SECRET_KEY=<aws_secret_key>
ISSUER_KMS_AWS_REGION=<aws_region> # if this value is `local` then `ISSUER_KMS_AWS_URL` is used
ISSUER_KMS_AWS_URL=<aws_url> # aws secret store URL
```
Note:  `ISSUER_KMS_AWS_REGION=local` is for running tests.

2024-11-21 10:14 UTC, martinsaporiti commented on infrastructure/local/docker-compose-infra.yml
> +      - "4566:4566"
We need port forwarding because `localstack` is used for running tests and those tests are outside docker

2024-11-21 10:29 UTC, martinsaporiti commented on internal/kms/kms.go
> +	ETHAWSSecretManagerStorage ConfigProvider = "aws"
@OBrezhniev AWS KMS is something to talk about with @demonsh because KMS just supports ETH Keys. In my understanding we will support only SM.

2024-11-27 17:35 UTC, OBrezhniev approved these changes

2024-11-27 18:14 UTC, demonsh approved these changes

2024-12-02 09:48 UTC, merged